<Project Sdk="Ignitron.Mod.Sdk/0.8.12">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>EvesThunder</RootNamespace>
        <Version>1.0.0</Version>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <GameDirectory>/beeg/Games/Launchers/Steam/steamapps/common/Allumeria/</GameDirectory>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Allumeria">
        <HintPath>\beeg\Games\Launchers\Steam\steamapps\common\Allumeria\Allumeria.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <None Remove="res\ignitron\evelyntsmg.EvesThunder\textures\atlas\items\talking_block.png" />
      <None Remove="Properties\launchSettings.json" />
    </ItemGroup>
</Project>
